apiVersion: v1
kind: Namespace
metadata:
  name: redis-demo
  labels:
    tenant: redis-demo
    tenant-id: "002"
    isolation: strict
    managed-by: kustomize
    pod-security.kubernetes.io/enforce: baseline
