apiVersion: v1
kind: Namespace
metadata:
  name: postgresql-demo
  labels:
    tenant: postgresql-demo
    tenant-id: "001"
    isolation: strict
    managed-by: kustomize
    pod-security.kubernetes.io/enforce: baseline
