apiVersion: v1
kind: ResourceQuota
metadata:
  name: tenant-quota
  namespace: tenant-base
spec:
  hard:
    requests.cpu: "4"
    limits.cpu: "8"
    requests.memory: "8Gi"
    limits.memory: "16Gi"
    requests.storage: "100Gi"
    persistentvolumeclaims: "10"
    pods: "50"
    services: "20"
    services.loadbalancers: "0"
    services.nodeports: "0"
    secrets: "50"
    configmaps: "50"
